# General formatting + YAML
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key

# YAML linting
-   repo: https://github.com/adrienverge/yamllint
    rev: 'v1.31.0'
    hooks:
    -   id: yamllint

# JavaScript & TypeScript linting
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.40.0'
    hooks:
    -   id: eslint

#Python
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.269'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
    
-   repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
    -   id: black
